//library for converting keystrokes to conventional note strings and octave controls for use with tone.js
const keyLib = {
    'a' : 'C',
    'w' : 'C#',
    's' : 'D',
    'e' : 'Eb',
    'd' : 'E',
    'f' : 'F',
    't' : 'F#',
    'g' : 'G',
    'y' : 'Ab',
    'h' : 'A',
    'u' : 'Bb',
    'j' : 'B',
    'k' : 'C',
    'o' : 'C#',
    'l' : 'D',
    'p' : 'Eb',
    ';' : 'E',
}